name: Webdriverio Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20.
        - name: Install
          run: npm ci
        - name: Run test
          run: npm run test
      
        - name: Create report
          if: always()
          run: npm run allure:generate
        - name: Upload artifact allure-report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: allure-report
            path: ./allure-report

        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-report


  docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t wdio-test . 

      - name: Run Webdriverio tests in Docker
        run: |
          docker run --rm wdio-test